---
- hosts: "{{ serv }}"
  remote_user: "{{ user }}"
  become: true
  become_method: sudo
  become_user: root
  
  tasks:
  - name: Copy files and backup the files if exist
    copy: src=/root/file1 dest=/tmp backup=yes force=no
