---
- name: This playbook is to copy files from source to destinatoin
  hosts: all
 
  tasks:
- name: Copy File on Remote
  copy: src="{{ item }}" dest=/root/jack/ mode=0755 remote_src=True
  with_fileglob:
      - "/root/subham/*"
