---
- hosts: "{{ serv }}"
  gather_facts: True
  remote_user: "{{ user }}"
  become: true
  become_method: sudo
  become_user: root
    
  tasks:
  - name: Adding users
    user: name={{ item.name }} update_password=always password=vagrant state=present groups={{ item.groups }} 
    with_items: 
      - { name: 'testuser1', groups: 'root' }
      - { name: 'testuser2', groups: 'root' }
      - { name: 'baso', groups: 'root' }
      - { name:  'subh', groups: 'root' }
      - { name:  'ansible', groups: 'root' }
      - { name : 'world', groups: 'root' }
      - { name : 'ram', groups: 'root' }
      - { name : 'rahim', groups: 'root' }
      - { name : 'Hari', groups: 'root' }
      - { name : 'rahul', groups: 'root' }
      - { name : 'rashmi', groups: 'root' }
      - { name : 'ramesh', groups: 'root' }
      - { name : 'vagrant', groups: 'vagrant' }
