---
- hosts: all
  gather_facts: True
  remote_user: "{{ user }}"
  become: true
  become_method: sudo
  become_user: root
    
  tasks:
  - name: Adding users
    user: name={{ item.name }} update_password=always password=vagrant state=present groups={{ item.groups }} 
    with_items: 
      - { name: 'testuser1', groups: 'ssh' }
      - { name: 'testuser2', groups: 'root' }
      - { name: 'baso', groups: 'ssh' }
      - { name:  'subh', groups: 'root' }
      - { name:  'ansible', groups: 'ssh' }
