---
- name: This playbook is to create group and user in desired server
  hosts: "{{ serv }}"
  remote_user: "{{ user }}"
  gather_facts: True
  become: True
  become_method: sudo
  become_user: root
 
  tasks:
  - name: Create group
    group:
    name: {{ item }}
    state: present
    with_items:
        - galaxy
        - remote
       
  - name: Create user
    user:
    name: {{ item }}
    groups: galaxy
    state: present 
    with_items:
        - ram
        - rahim
