---
- hosts: "{{ serv }}"
  gather_facts: True
  become: true
  become_method: sudo
  become_user: root
  any_errors_fatal: false
  ignore_errors: false
  
  tasks:
  - name: Installing softwares
    yum: name={{ item }} state=installed 
    with_items:
     - htop
     - vim
     - git
     - mlocate
