---
- hosts: "{{ serv }}"
  remote_user: "{{ user }}"
  gather_facts: True
  become: true
  become_method: sudo
  become_user: root
  
  tasks:
  - name: Create Group
    group:
    name: galaxy
    state: present
