---
- hosts: all
  gather_facts: True
  remote_user: "{{ user }}"
  become: true
  become_method: sudo
  become_user: root
  vars:
   password: vagrant
  
  tasks:
  - name: Adding users
    user: name={{ item.name }} state=present groups={{ item.groups }} update_password=always password={{ password }}
    with_items: 
      - { name: 'testuser1', groups: 'wheel' }
      - { name: 'testuser2', groups: 'root' }
      - { name: 'baso', groups: 'wheel' }
      - { name:  'subh', groups: 'root' }
      - { name:  'ansible', groups: 'wheel' }
