---
- hosts: "{{ serv }}"
  remote_user: "{{ user }}"
  gather_facts: True
  become: true
  become_method: sudo
  become_user: root
  
  tasks:
  - name: Installing Softwares
    yum:
    name: {{ item }}
    state: installed
    with_items:
     - git
     - vim
     - htop
     - nmap
