---
- hosts: "{{ serv }}"
  gather_facts: True
  become: true
  become_method: sudo
  become_user: root
  
  tasks:
  - name: Installing softwares
    yum: name={{ item }} state=installed
    ignore_errors: true
    with_items:
     - htop
     - vim
     - git
     - mlocate
