---
- name: This playbook is to create group and user in desired server
  hosts: "{{ serv }}"
  remote_user: "{{ user }}"
  gather_facts: True
  become: True
  become_method: sudo
  become_user: root
 
  tasks:
  - name: Create group
    group:
    name: {{ item.group }}
    state: present
    with_items:
       - "{ group: 'galaxy'}"
       - "{ group: 'remote' }"
       
  - name: Create user
    user:
    name: {{ item.name }}
    group: galaxy
    state: present 
    with_items:
       - "{ name: 'ram' }"
       - "{ name: 'rahim' }"
