---
- hosts: all
  gather_facts: True
  remote_user: "{{ user }}"
  become: true
  become_method: sudo
  become_user: root
  
  tasks:
  - name: Creating folder structure
    file: 
    src: '/tmp/{{ item.src }}'
    dest: '/tmp/{{ item.dest }}'
    mode: 777
    owner: awx
    group: awx
    state: directory
    with_items:
      - { src: 'dir1' dest: 'dest1' }
      - { src: 'dir2' dest: 'dest2' }
