---
- hosts: all
  gather_facts: True
  remote_user: "{{ user }}"
  become: true
  become_method: sudo
  become_user: root
  
  tasks:
  - name: Creating folder structure
    file: state=directory mode=775 owner=awx group=awx recurse=yes dest=/tmp/{{ item.dest }}
    with_items:
        - { dest: 'dest1' }
        - { dest: 'dest2' }
        - { dest: 'subham' }
        - { dest: 'madhu' }
        - { dest: 'family'}
