---
- hosts: "{{ serv }}"
  gather_facts: True
  remote_user: "{{ user }}"
  become: true
  become_method: sudo
  become_user: root 
  vars:
   pkg :
    - vsftpd
    - squid
    - mysql
    - ntp
   client:
    - jenkins
    - docker
        
  tasks:
  - name: Ensure vsftp/mysql/ntp and squid are installed
    action: yum name={{ item }} state=installed
    with_items: "{{ pkg }}"
    
  - name: Ensure Jenkins and Dockers are installed
    action: yum name={{ item }} state=installed
    with_items: "{{ client }}"

    notify: 
    - start squid
    - start ntpd
    - start docker
      
  handlers:
   - name: start squid
     service: name=squid state=started
   - name: start ntpd
     service: name=ntpd state=started
   - name: start docker
     service: name=docker state=started
     
