---
- hosts: "{{ serv }}"
  gather_facts: True
  remote_user: "{{ user }}"
  become: true
  become_method: sudo
  become_user: root 
  vars:
   pkg :
    - vsftpd
    - squid
    - mysql
    - ntp
    - java
   client:
    - jenkins
    - docker
        
  tasks:
  - name: Ensure vsftp/mysql/ntp and squid are installed
    action: yum name={{ item }} state=installed
    with_items: "{{ pkg }}"
    
  - name: Ensure Jenkins and Dockers are installed
    action: yum name={{ item }} state=installed
    with_items: "{{ client }}"
    
  - name: Running post install commands
    command: {{ item }}
    with_items:
     - iptables -F 
     - systemctl start jenkins

    notify: 
    - start squid
    - start ntpd
    - start docker
    - start jenkins
      
  handlers:
   - name: start squid
     service: name=squid state=started
   - name: start ntpd
     service: name=ntpd state=started
   - name: start docker
     service: name=docker state=started
   - name: start jenkins
     service: name=jenkins state=started
