---
- name: Running role playbook for testing
  hosts: "{{ serv }}"
  remote_user: "{{ Remote_user }}"
  gather_facts: True
  become: yes
  become_user: root
  become_method: sudo
  
  tasks:
  roles:
   - web
