---
- hosts: "{{ serv }}"
  gather_facts: True
  remote_user: "{{ user }}"
  become: true
  become_method: sudo
  become_user: root
  
  tasks:
  - name: Ensure mysql is installed
    action: yum name={{ item }} state=installed
    with_items:
      - mysql
      - ntp
  - name: Ensure ntp is running
    service: name=ntpd state=running enabled=yes
  - name: Ensure vsftp installed
    action: yum name={{ item }} state=installed
    with_items:
      - vsftpd
      - squid
  - name: Ensure Vsftpd and squid is running
    service: name={{ item }} enabled=yes
    with_items:
      - vsftpd
      - squid
