---
- hosts: all
  gather_facts: True
  remote_user: "{{ user }}"

  tasks:
  -name: install Git and ftp packages 
   yum: 
   name: "{{ item }}"
   state=installed
   with_items:
   - unzip
   - tar
   - htop
   - git 
   - iotop
