---
- hosts: all
  gather_facts: True
  remote_user: "{{ user }}"

  tasks:
  - name: "Install Common Libraries from CentOS mirror"
    yum: state=present name={{ item }}
    with_items:
       - sudo
       - vim
       - gcc
       - gcc-c++
       - unzip
       - wget
       - tar
