---
- hosts: "{{ serv }}"
  remote_user: "{{ user }}"
  gather_facts: True
  become: true
  become_method: sudo
  become_user: root
  
  tasks:
  - name: this is sudo test
    action: file name=/tmp/sudotest.txt state=file owner=vagrant group=root
   
