---
- hosts: "{{ serv }}"
  remote_user: "{{ user }}"
  become: true
  become_method: sudo
  become_user: root
  
  tasks:
  - name: this is sudo test
    action: file name=/tmp/sudotest state=directory owner=vagrant group=root
   
