---
- hosts: all
  gather_facts: True

  tasks:
  - git: repo=https://github.com/subhamproject/Testrepo.git
       dest=/tmp/git1
       force=no
       accept_hostkey=yes
    
  - name: copy file
    shell:  find /tmp/git1/ -type f -name "*.yml" -exec rsync -azr {}  /tmp/mytest/ \;
