---
- hosts: all
  gather_facts: True
  remote_user: "{{ user }}"
  become: true
  become_method: sudo
  become_user: root
  include_vars: vars.yml
  
  tasks:
  - name: adding user with inclue vars
    user: name={{ item.username }} state=present shell=/bin/ksh createhome=yes comment='create with ansible' group={{ item.groupname }}
    with_items: 
      - '{{users}}'
      - '{{groups}}'
