---
- hosts: all
  gather_facts: True
  remote_user: "{{ user }}"
  become: true
  become_method: sudo
  become_user: root
  
  
  tasks:
  - include_vars: vars.yml
  
  - name: adding user with inclue vars
    user: name={{ item.username }} state=present shell=/bin/ksh createhome=yes comment='create with ansible' 
    with_items: '{{users}}'
      
