---
- name: install ntp
  yum: name=ntp state=present
  
- name: start ntp
  service: name=ntp state=started
  notify:
   - start ntp
   
 - name: copying files
   copy: src=main.yml dest=/tmp/subham/
