---
- hosts: "{{ serv }}"
  remote_user: "{{ user }}"
  gather_facts: True
  become: yes
  become_method: sudo
  become_user: root
  
  - name: create users
    user: name={{ users }} shell=/bin/bash createhome=yes group=admin
